name: "Bug Report"
description: "File a bug report"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide a proper title and description to the issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue properly.
      placeholder: Tell us what error happened!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What's the expected behavior?
      description: Tell us what is the expected behavior.
      placeholder: Describe the expected behavior.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/itsvks19/LayoutEditor/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true